# Customer Churn Data Cleaning and Preparation

## Project Overview

Customer Churn occurs when customers stop using a company's products or services.
This project focuses on cleaning and preparing a Telecommunicatins customer dataset for further analysis.
The main goal is to identify and address data quality issues such as 
Missing Values

Duplicate Records

Incorrect Data Types

Inconsistent Values 

Potential Outliers 

The cleaned dataset will provide a reliable foundation for subsequent Customer churn anlaysis.

## Busines  Problem 

Telecommunication companies need reliable customer data to understand customer behaviour and identify factors associated with customer churn 

Before performing analysis , the dataset must be examined and cleaned to ensure that the results are accurate and trustworthy.

This project therefore focuses on systematically assessing and improving the quality of the customer churn dataset

## Project Objectives 
The objectives of thus projects are to :

1. Understand the structure and characteristics of the raw dataset
2. Assess the quality of the data
3. Identify missing values and determine appropriate ways of handling them
4. Identify and investigate duplicated records from the dataset
5. Correct inappropriate and inconsistent data types
6. Identify inconsistent categorical values
7. Investigate potential outliers in the dataset
8. Validate the cleaned dataset
9. Save the cleaned dataset for future analysis

## Data Description

The dataset contains customer-level information from a telecommunication company.
It includes information about:

1. Customer Demographics
2. Services subscribed to
3. Contact Information
4. Payment Methods
5. Customer Tenure
6. Monthly Charges
7. Total Charges
8. Customer Churn Status

**N/B**
The target variable is *Churn* , which indicates whether a customer left the company.

## Data Source

The dataset used in this project is the TELCO CUSTOMER CHURN dataset , originally provided by **IBM**

Source: Telco Customer churn dataset

Original file: "Telco_Customer_churn.csv"

Dataset size : 7043 Records and 21 Variables

## data Inspection 

### Import Libraries

In [1]:
# import important libraries

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

### loading the dataset

In [2]:
df=pd.read_csv("Telco-Customer-Churn.csv")

# read the dataset , top 5

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
# Identifying the number of rows and columns 
df.shape

(7043, 21)

In [4]:
# Identifying the column names within the dataset
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [5]:
# getting the dataset summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## DATA QUALITY ASSESSMENT

### STEP2: Assess Data's Missing Values 

Missing values can affect analysis and may need to be handled before the dataset is used for further analysis or modelling.

In this data cleaning process , we checked for data Completeness

FALSE: Not Missing
TRUE: Missing value

Observation : The dataset contained no missing values across all the 21 Variables, the dataset is 100% complete

In [6]:
# checking for missing values 
df.isnull()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
# Columns with the most missing values 

df.isnull().sum().sort_values(ascending=False)

customerID          0
DeviceProtection    0
TotalCharges        0
MonthlyCharges      0
PaymentMethod       0
PaperlessBilling    0
Contract            0
StreamingMovies     0
StreamingTV         0
TechSupport         0
OnlineBackup        0
gender              0
OnlineSecurity      0
InternetService     0
MultipleLines       0
PhoneService        0
tenure              0
Dependents          0
Partner             0
SeniorCitizen       0
Churn               0
dtype: int64

In [9]:
# getting a sample of the data to understand the structure

df.sample(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5257,6029-WTIPC,Male,1,No,No,37,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,101.10,3744.05,Yes
4736,3050-RLLXC,Female,0,Yes,Yes,56,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),81.25,4620.4,No
6797,8725-JEDFD,Male,0,No,No,27,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,69.05,1793.25,No
6195,8111-RKSPX,Male,0,No,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),72.20,305.55,Yes
3965,3692-JHONH,Female,1,Yes,No,52,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Electronic check,106.50,5621.85,No
5115,6374-AFWOX,Male,0,Yes,No,46,Yes,No,DSL,Yes,...,Yes,Yes,No,No,Two year,No,Mailed check,65.65,3047.15,No
1037,4581-LNWUM,Female,0,No,No,13,No,No phone service,DSL,No,...,Yes,No,Yes,Yes,Month-to-month,No,Electronic check,49.15,649.4,No
5870,0568-ONFPC,Male,0,Yes,Yes,5,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.90,135,Yes
3742,9822-WMWVG,Female,0,No,No,41,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,No,Month-to-month,Yes,Electronic check,106.50,4282.4,No
2609,4446-BZKHU,Male,0,Yes,No,61,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,105.55,6281.45,Yes

In [10]:
## Checking for blank values

df["TotalCharges"].astype(str).str.strip().eq("").sum()

11

In [11]:
## Checking the entire dataset columns

(df.astype(str).apply(lambda x: x.str.strip().eq("")).sum())

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

#### How many columns have some missing values / blank values

from the above information , we observe that **TotalCharges** columns has the highest number of missing values with **11**.

The rest of the columns have *0* missing values 

*ACTION*

The missing values in the *TotalCharges* column will be further investigated to determine whether they represent genuine missing information or another data quality issue

In [18]:
## Checking affected columns with blank values

df.loc[
    df["TotalCharges"].astype(str).str.strip() == "",
    ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
]

      customerID  tenure  MonthlyCharges TotalCharges Churn
488   4472-LVYGI       0           52.55                 No
753   3115-CZMZD       0           20.25                 No
936   5709-LVOEQ       0           80.85                 No
1082  4367-NUYAO       0           25.75                 No
1340  1371-DWPAZ       0           56.05                 No
3331  7644-OMVMY       0           19.85                 No
3826  3213-VVOLG       0           25.35                 No
4380  2520-SGTTA       0           20.00                 No
5218  2923-ARZLG       0           19.70                 No
6670  4075-WKNIU       0           73.35                 No
6754  2775-SEFEE       0           61.90                 No

#### Finding

The blank-value check identified **11 blank values in the `TotalCharges` column**.

Further investigation showed that all 11 affected records have a **tenure of 0 months** and valid `MonthlyCharges` values.

Since `TotalCharges` represents the accumulated charges over the customer's tenure, a tenure of 0 indicates that these customers are new accounts with no accumulated charges.

### Cleaning Decision

The 11 blank `TotalCharges` values will be converted to **0** during the data-cleaning stage.

This treatment is based on the observed relationship between `tenure = 0` and the absence of accumulated total charges. The raw dataset will be preserved, and the correction will be applied to the cleaned dataset.

### STEP2.2 CHECKING FOR DUPLICATED VALUES

Duplicate records can lead to inaccurate analysis because a customer may be counted more than once .

Therefore , duplicate rows were checked before proceeding with further analysis

In [12]:
# Checking and investigating duplicate records

df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [13]:
# Total records with duplicated data

df.duplicated().sum()

0

##### OBSERVATION

The Telco-Customer-churn dataset contains **0** duplicated records.

This is useful and important for analysis 

Conclusion

No Duplicate rows were identified.

Therefore no duplicate records need to be removed , hence the dataset can proceed to the next stage of the data cleaning process.

### CHECKING DATA TYPES

This step is crucial because each variable should be have an appropriate data type for analysis

Numerical variables should be stored as Numeric data types 

Categorical variables should be stored generally as strings or categorical variables

In [14]:
# CHECKING FOR DATA TYPES

df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [22]:
## TAKING NOTE OF THE TOTALCHARGES COLUMN
## LET'S OBSERVE IT DATA TYPE
df["TotalCharges"].dtype

dtype('O')

In [23]:
df["TotalCharges"].tail()

7038    1990.5
7039    7362.9
7040    346.45
7041     306.6
7042    6844.5
Name: TotalCharges, dtype: object

#### *OBSERVATIOM*

The **TOtalCharges** column is stored as *Object* data type , although it represents numerical monetary  customer charges

This is associated with the 11 blank values identified earlier in the column 

The blank values prevent pandas from treating the entire column as numeric

ACTION 

The TotalCharges column will be converted to a  numeric data type after investigating the values that prevet direct conversion

### CONSISTENCY CHECK 

We investigate the consistency of our data in the categrical columns 

some of the key categorical columns are 

Gender

Partner

PhoneService

OnlineSecurity

TechSupport

StreamingTv

StreamingMovies


PaperlessBilling

Churn

In [26]:
# checking gender
df["gender"].value_counts()

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [27]:
# check for partner value counts
df["Partner"].value_counts()

Partner
No     3641
Yes    3402
Name: count, dtype: int64

In [28]:
## check for phone service

df["PhoneService"].value_counts()

PhoneService
Yes    6361
No      682
Name: count, dtype: int64

In [29]:
# checking for Online security value counts
df["OnlineSecurity"].value_counts()

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

In [30]:
## check for techsupport value counts
df["TechSupport"].value_counts()

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

In [31]:
## check for paperlessbilling

df["PaperlessBilling"].value_counts()

PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

In [32]:
# check for churn value counts
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64